#pragma once

//플레이어 직업
enum OCCUPATION { WARRIOR, WIZARD, THIEF, OCCUPATION_END };
//몬스터의 서식지
enum HABITAT { BIGINNER = 1, INTERMEDIATE, INTENCE, HELL , HABITAT_END};

//속성
enum ELEMENT { FIRE, WATER, GRASS, EARTH, ELEMENT_END };

enum COMBAT { COMBAT_WIN, COMBAT_LOSE, COMBAR_RUN, COMBAT_END };


